config/routes.rb
Avo::Engine.routes.draw do
  root "home#index"

  get "resources", to: redirect("/avo")

  scope "resources", as: "resources" do
    # Attachments
    get "/:resource_name/:id/active_storage_attachments/:attachment_name/:signed_attachment_id", to: "attachments#show"
    delete "/:resource_name/:id/active_storage_attachments/:attachment_name/:signed_attachment_id", to: "attachments#destroy"

    # Actions
    get "/:resource_name(/:id)/actions/:action_id", to: "actions#show"
    post "/:resource_name(/:id)/actions/:action_id", to: "actions#handle"

    # Generate resource routes as below:
    # resources :posts
    instance_eval(&Avo::App.draw_routes)

    # Relations
    get "/:resource_name/:id/:related_name/new", to: "relations#new"
    get "/:resource_name/:id/:related_name/", to: "relations#index"
    get "/:resource_name/:id/:related_name/:related_id", to: "relations#show"
    post "/:resource_name/:id/:related_name", to: "relations#create"
    delete "/:resource_name/:id/:related_name/:related_id", to: "relations#destroy"
  end

  # get '/avo-api/search',                  to: 'search#index'
  # get '/avo-api/:resource_name/search',   to: 'search#resource'

  # Tools
  # get '/avo-tools/resource-overview', to: 'resource_overview#index'
end

app/controllers/avo/actions_controller.rb
require_dependency "avo/application_controller"

module Avo
  class ActionsController < ApplicationController
    before_action :set_resource_name
    before_action :set_resource
    before_action :set_action, only: [:show, :handle]

    def show
      @model = ActionModel.new @action.get_attributes_for_action
    end

    def handle
      resource_ids = action_params[:fields][:resource_ids].split(",").map(&:to_i)
      models = @resource.model_class.find resource_ids

      fields = action_params[:fields].select do |key, value|
        key != "resource_ids"
      end

      performed_action = @action.handle_action(models: models, fields: fields)

      respond performed_action.response
    end

    private

    def action_params
      params.permit(:resource_name, :action_id, fields: {})
    end

    def set_action
      action_class = params[:action_id].gsub("avo_actions_", "").classify.safe_constantize

      if params[:id].present?
        model = @resource.model_class.find params[:id]
      end

      @action = action_class.new(model: model, resource: resource, user: _current_user)
    end

    def respond(response)
      response[:type] ||= :reload
      response[:message_type] ||= :notice
      response[:message] ||= I18n.t("avo.action_ran_successfully")

      if response[:type] == :download
        return send_data response[:path], filename: response[:filename]
      end

      respond_to do |format|
        format.html do
          if response[:type] == :redirect
            path = response[:path]

            if path.respond_to? :call
              path = instance_eval(&path)
            end

            redirect_to path, "#{response[:message_type]}": response[:message]
          elsif response[:type] == :reload
            redirect_back fallback_location: resources_path(@resource.model_class), "#{response[:message_type]}": response[:message]
          end
        end
      end
    end
  end
end

app/controllers/avo/attachments_controller.rb
require_dependency "avo/application_controller"

module Avo
  class AttachmentsController < ApplicationController
    before_action :set_resource_name, only: :destroy
    before_action :set_resource, only: :destroy
    before_action :set_model, only: :destroy

    def show
    end

    def destroy
      blob = ActiveStorage::Blob.find(params[:signed_attachment_id])
      attachment = blob.attachments.find_by record_id: params[:id], record_type: @model.class.to_s

      if attachment.present?
        attachment.destroy

        redirect_to params[:referrer] || resource_path(@model), notice: t("avo.attachment_destroyed")
      else
        redirect_back fallback_location: resource_path(@model), notice: t("avo.failed_to_find_attachment")
      end
    end
  end
end

app/controllers/avo/home_controller.rb
require_dependency "avo/application_controller"

module Avo
  class HomeController < ApplicationController
    def index
      if Avo.configuration.home_path.present?
        redirect_to Avo.configuration.home_path
      elsif !Rails.env.development?
        @page_title = "Get started"
        redirect_to resources_path Avo::App.get_resources.min_by { |resource| resource.route_key }.model_class
      end
    end
  end
end

app/controllers/avo/relations_controller.rb
require_dependency "avo/base_controller"

module Avo
  class RelationsController < BaseController
    before_action :set_model, only: [:show, :index, :new, :create, :destroy]
    before_action :set_related_resource_name
    before_action :set_related_resource
    before_action :hydrate_related_resource
    before_action :set_related_model, only: [:show]
    before_action :set_attachment_class
    before_action :set_attachment_resource
    before_action :set_attachment_model, only: [:create, :destroy]
    before_action :set_reflection, only: [:index]

    def index
      @parent_resource = @resource.dup
      @resource = @related_resource
      @parent_model = @parent_resource.model_class.find(params[:id])
      @parent_resource.hydrate(model: @parent_model)
      @query = @parent_model.public_send(params[:related_name])

      super
    end

    def show
      @reflection = params[:related_name]
      @resource, @model = @related_resource, @related_model

      super
    end

    def new
      query = @authorization.apply_policy @attachment_class

      @options = query.all.map do |model|
        {
          value: model.id,
          label: model.send(@attachment_resource.class.title)
        }
      end
    end

    def create
      if reflection_class == "HasManyReflection"
        @model.send(params[:related_name].to_s) << @attachment_model
      else
        @model.send("#{params[:related_name]}=", @attachment_model)
      end

      respond_to do |format|
        if @model.save
          format.html { redirect_to resource_path(@model), notice: t("avo.attachment_class_attached", attachment_class: @attachment_class) }
          format.json { render :show, status: :created, location: resource_path(@model) }
        else
          format.html { render :new }
          format.json { render json: @model.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      if reflection_class == "HasManyReflection"
        @model.send(params[:related_name].to_s).delete @attachment_model
      else
        @model.send("#{params[:related_name]}=", nil)
      end

      respond_to do |format|
        format.html { redirect_to params[:referrer] || resource_path(@model), notice: t("avo.attachment_class_detached", attachment_class: @attachment_class) }
      end
    end

    private

    def set_attachment_class
      @attachment_class = @model._reflections[params[:related_name].to_s].klass
    end

    def set_attachment_resource
      @attachment_resource = App.get_resource_by_model_name @attachment_class
    end

    def set_attachment_model
      @attachment_model = @model._reflections[params[:related_name].to_s].klass.find attachment_id
    end

    def set_reflection
      @reflection = @model._reflections[params[:related_name].to_s]
    end

    def attachment_id
      params[:related_id] || params.require(:fields).permit(:related_id)[:related_id]
    end

    def reflection_class
      reflection = @model._reflections[params[:related_name]]

      klass = reflection.class.name.demodulize.to_s
      klass = reflection.through_reflection.class.name.demodulize.to_s if klass == "ThroughReflection"

      klass
    end
  end
end

app/controllers/avo/resources_controller.rb
require_dependency "avo/base_controller"

module Avo
  class ResourcesController < BaseController
  end
end

app/controllers/avo/search_controller.rb
require_dependency "avo/application_controller"

module Avo
  class SearchController < ApplicationController
    # before_action :authorize_user

    def index
      @authorization.set_record(resource_model).authorize_action :index
      resources = []

      App.get_resources
        .select { |resource| resource.search.present? }
        .select { |resource| AuthorizationService.authorize_action _current_user, resource.model, "index" }
        .each do |resource_model|
          found_resources = add_link_to_search_results(search_resource(resource_model), resource_model)
          resources.push({
            label: resource_model.name,
            resources: found_resources
          })
        end

      render json: {
        resources: resources
      }
    end

    def resource
      render json: {
        resources: add_link_to_search_results(search_resource(avo_resource), avo_resource)
      }
    end

    private

    def add_link_to_search_results(resources, avo_resource)
      resources.map do |model|
        {
          id: model.id,
          search_label: model.send(avo_resource.class.title),
          link: "/resources/#{model.class.to_s.singularize.underscore}/#{model.id}"
        }
      end
    end

    def search_resource(avo_resource)
      avo_resource.query_search(query: params[:q], via_resource_name: params[:via_resource_name], via_resource_id: params[:via_resource_id], user: _current_user)
    end

    # def authorize_user
    #   return if params[:action] == 'index'

    #   action = params[:action] == 'resource' ? :index : params[:action]

    #   return render_unauthorized unless AuthorizationService::authorize_action _current_user, avo_resource.model, action
    # end
  end
end

app/helpers/avo/actions_helper.rb
module Avo
  module ActionsHelper
  end
end

app/helpers/avo/application_helper.rb
module Avo
  module ApplicationHelper
    include ::Webpacker::Helper
    include ::Pagy::Frontend

    def current_webpacker_instance
      Avo.webpacker
    end

    def render_license_warnings
      render partial: "avo/sidebar/license_warnings", locals: {
        license: Avo::App.license.properties
      }
    end

    def render_license_warning(title: "", message: "", icon: "exclamation")
      render partial: "avo/sidebar/license_warning", locals: {
        title: title,
        message: message,
        icon: icon
      }
    end

    def empty_state(resource_name)
      render partial: "avo/partials/empty_state", locals: {resource_name: resource_name}
    end

    def turbo_frame_start(name)
      "<turbo-frame id=\"#{name}\">".html_safe if name.present?
    end

    def turbo_frame_end(name)
      "</turbo-frame>".html_safe if name.present?
    end

    def a_button(label = nil, **args, &block)
      args[:class] = button_classes(args[:class], color: args[:color], variant: args[:variant], size: args[:size])

      locals = {
        label: label,
        args: args
      }

      if block
        render layout: "avo/partials/a_button", locals: locals do
          capture(&block)
        end
      else
        render partial: "avo/partials/a_button", locals: locals
      end
    end

    def a_link(label, url = nil, **args, &block)
      args[:class] = button_classes(args[:class], color: args[:color], variant: args[:variant], size: args[:size])

      if block
        url = label
      end

      locals = {
        label: label,
        url: url,
        args: args
      }

      if block
        render layout: "avo/partials/a_link", locals: locals do
          capture(&block)
        end
      else
        render partial: "avo/partials/a_link", locals: locals
      end
    end

    def button_classes(extra_classes = nil, color: nil, variant: nil, size: :md)
      classes = "inline-flex flex-grow-0 items-center text-sm font-bold leading-none fill-current whitespace-nowrap transition duration-100 rounded-lg shadow-xl transform transition duration-100 active:translate-x-px active:translate-y-px cursor-pointer disabled:cursor-not-allowed #{extra_classes}"

      if color.present?
        if variant.present? && (variant.to_sym == :outlined)
          classes += " bg-white border"

          classes += " hover:border-#{color}-700 border-#{color}-600 text-#{color}-600 hover:text-#{color}-700 disabled:border-gray-300 disabled:text-gray-600"
        else
          classes += " text-white bg-#{color}-500 hover:bg-#{color}-600 disabled:bg-#{color}-300"
        end
      else
        classes += " text-gray-700 bg-white hover:bg-gray-100 disabled:bg-gray-300"
      end

      size = size.present? ? size.to_sym : :md
      classes += case size
      when :xs
        " p-2 py-1"
      when :sm
        " p-3"
      when :md
        " p-4"
      else
        " p-4"
      end

      classes
    end

    def svg(file_name, **args)
      options = {}
      options[:class] = args[:class].present? ? args[:class] : "h-4 mr-1"
      options[:class] += args[:extra_class].present? ? " #{args[:extra_class]}" : ""

      # Create the path to the svgs directory
      file_path = "#{Avo::Engine.root}/app/packs/svgs/#{file_name}"
      file_path = "#{file_path}.svg" unless file_path.end_with? ".svg"

      # Create a cache hash
      hash = Digest::MD5.hexdigest "#{file_path.underscore}_#{options}"

      svg_content = Avo::App.cache_store.fetch "svg_file_#{hash}", expires_in: 1.year, cache_nils: false do
        if File.exist?(file_path)
          file = File.read(file_path)

          # parse svg
          doc = Nokogiri::HTML::DocumentFragment.parse file
          svg = doc.at_css "svg"

          # attach options
          options.each do |attr, value|
            svg[attr.to_s] = value
          end

          # cast to html
          doc.to_html.html_safe
        end
      end

      return "(not found)" if svg_content.to_s.blank?

      svg_content
    end

    def input_classes(extra_classes = "", has_error: false)
      classes = "appearance-none inline-flex bg-blue-gray-100 disabled:bg-blue-gray-300 disabled:cursor-not-allowed focus:bg-white text-blue-gray-700 disabled:text-blue-gray-700 rounded-md py-2 px-3 leading-tight border outline-none outline"

      classes += if has_error
        " border-red-600"
      else
        " border-blue-gray-300"
      end

      classes += " #{extra_classes}"

      classes
    end
  end
end

app/helpers/avo/attachments_helper.rb
module Avo
  module AttachmentsHelper
  end
end

app/helpers/avo/resources_helper.rb
module Avo
  module ResourcesHelper
    def resource_table(resources, resource)
      render partial: "avo/partials/resource_table", locals: {
        resources: resources,
        resource: resource
      }
    end

    def resource_grid(resources, resource)
      render partial: "avo/partials/resource_grid", locals: {
        resources: resources,
        resource: resource
      }
    end

    def index_field(field, index, resource)
      component = field.component_name(:index)

      if Object.const_defined? component
        render component.safe_constantize.new(field: field, resource: resource, index: index)
      else
        render partial: field.partial_path_for(:index), locals: {
          field: field,
          index: index,
          resource: resource
        }
      end
    end

    def show_field(field, index, resource)
      component = field.component_name(:show)

      if Object.const_defined? component
        render component.safe_constantize.new(field: field, resource: resource, index: index)
      else
        render partial: field.partial_path_for(:show), locals: {
          field: field,
          index: index,
          resource: resource
        }
      end
    end

    def edit_field(field, index, resource, form, displayed_in_modal: false)
      component = field.component_name(:edit)

      if Object.const_defined? component
        render component.safe_constantize.new(field: field, resource: resource, index: index, form: form, displayed_in_modal: displayed_in_modal)
      else
        render partial: field.partial_path_for(:edit), locals: {
          field: field,
          index: index,
          resource: resource,
          form: form,
          displayed_in_modal: displayed_in_modal
        }
      end
    end

    def index_field_wrapper(**args, &block)
      render Index::FieldWrapperComponent.new(**args) do
        capture(&block)
      end
    end

    def show_field_wrapper(**args, &block)
      render Show::FieldWrapperComponent.new(**args) do
        capture(&block)
      end
    end

    def edit_field_wrapper(**args, &block)
      render Edit::FieldWrapperComponent.new(**args) do
        capture(&block)
      end
    end

    def filter_wrapper(name: nil, index: nil, **args, &block)
      render layout: "layouts/avo/filter_wrapper", locals: {
        name: name,
        index: index
      } do
        capture(&block)
      end
    end

    def item_selector_init(resource)
      "data-resource-name='#{resource.plural_name.downcase}' data-resource-id='#{resource.model.id}' data-controller='item-selector'"
    end

    def item_selector_input(floating: false, size: :md)
      "<input type='checkbox'
        class='mx-3 #{"absolute inset-auto left-0 mt-2 z-10 hidden group-hover:block checked:block" if floating} #{size.to_sym == :lg ? "w-5 h-5" : "w-4 h-4"}'
        data-action='input->item-selector#toggle'
        title='#{t "avo.select_item"}'
        data-tippy='tooltip'
      />"
    end
  end
end

app/views/avo/partials/_a_button.html.erb
<% if (block = yield).empty? %>
  <%= button_tag label, **args %>
<% else %>
  <%= button_tag **args do %>
    <%= yield %>
  <% end %>
<% end %>

app/views/avo/partials/_a_link.html.erb
<% if (block = yield).empty? %>
  <%= link_to label, url, **args %>
<% else %>
  <%= link_to url, **args do %>
    <%= yield %>
  <% end %>
<% end %>

app/views/avo/partials/_alert.html.erb
<div data-controller="alerts" data-alerts-target="container" data-alert-type="<%= type %>" class="hidden"><%= message %></div>

app/views/avo/partials/_alerts.html.erb
<% flash.each do |type, message| %>
  <%= render partial: 'avo/partials/alert', locals: {type: type.to_sym, message: message} %>
<% end %>

app/views/avo/partials/_custom_tools_alert.html.erb
<div class="w-full inset-auto bottom-0 z-50 mb-4 opacity-75 hover:opacity-100 transition-opacity duration-150">
  <a href="https://avohq.io/pricing" target="_blank" class="rounded bg-green-700 text-white py-2 px-4 text-sm block items-center flex leading-tight">
    <%= svg "exclamation", class: "h-6 inline mr-2 text-bold flex-shrink-0" %> Warning. Your license is invalid or doesn't support custom tools. This page will not be visible in a production environment.
  </a>
</div>

app/views/avo/partials/_empty_state.html.erb
<%
  classes = 'absolute inset-auto left-1/2 top-1/2 transform -translate-x-1/2 -translate-y-1/2'
  translation_tag = params[:related_name].present? ? 'avo.no_related_item_found' : 'avo.no_item_found'
  label = t translation_tag, item: resource_name
%>
<div class="relative flex-1 py-12">
  <div class="relative block text-gray-300 h-64 w-full">
    <%= svg 'avocado', class: "#{classes} h-20 text-gray-400" %>
    <%= svg 'code', class: "#{classes} h-8 -ml-20 -mt-12" %>
    <%= svg 'fire', class: "#{classes} h-8 -ml-10 -mt-24" %>
    <%= svg 'color-swatch', class: "#{classes} h-8 ml-8 -mt-24" %>
    <%= svg 'globe', class: "#{classes} h-8 ml-20 -mt-12" %>
    <%= svg 'library', class: "#{classes} h-8 -ml-20 mt-4" %>
    <%= svg 'photograph', class: "#{classes} h-8 ml-20 mt-4" %>
  </div>
  <div class="relative block text-center text-lg text-gray-400 font-semibold -mt-10"><%= label %></div>
</div>

app/views/avo/partials/_footer.html.erb
<div class="text-center text-sm text-gray-700">
  <a href="https://avohq.io/" target="_blank">Avo</a> · &copy; <%= Date.today.year %> AvoHQ · v<%= Avo::VERSION %>
</div>

app/views/avo/partials/_header.html.erb
<%= link_to Avo.configuration.app_name, '/', class: 'text-green-600 font-semibold', target: :_blank %>

app/views/avo/partials/_logo.html.erb
<%= image_pack_tag 'logo.png', class: 'h-full', title: 'Avo' %>

app/views/avo/partials/_paginator.html.erb
<%
  per_page_options = [*Avo.configuration.per_page_steps, Avo.configuration.per_page.to_i, @index_params[:per_page].to_i]

  if @parent_resource.present?
    per_page_options.prepend Avo.configuration.via_per_page
  end

  per_page_options = per_page_options.sort.uniq
%>

<div class="bg-white px-4 flex items-center justify-between aborder-t aborder-blue-gray-200 sm:px-6 rounded-xl">
  <div class="hidden sm:flex-2 sm:flex sm:items-center sm:justify-between">
    <div>
      <div class="text-sm leading-5 text-blue-gray-600 flex items-center">
        <div class="mr-2"><%== pagy_info @pagy %></div>

        <div data-controller="per-page">
          <div class="flex items-center">
            <%= select_tag 'per_page',
              options_for_select(per_page_options, @index_params[:per_page]),
              class: 'appearance-none inline-flex bg-blue-gray-100 disabled:bg-blue-gray-400 disabled:cursor-not-allowed focus:bg-white text-blue-gray-700 disabled:text-blue-gray-600 rounded-md py-1 px-2 leading-tight border border-blue-gray-300 outline-none focus:border-blue-gray-400 outline w-16 mr-1 text-sm',
              data: {
                'turbo-frame': turbo_frame,
                'per-page-target': 'selector',
                action: 'change->per-page#reload'
              }
            %> <%= t('avo.per_page').downcase %>
          </div>

          <% per_page_options.each do |option| %>
            <% if @parent_resource.present? %>
              <%= link_to "Change to #{option} items per page", related_resources_path(@parent_resource.model, @resource.model_class, per_page: option, keep_query_params: true), class: 'hidden', 'data-per-page-option': option, 'data-turbo-frame': turbo_frame %>
            <% else %>
              <%= link_to "Change to #{option} items per page", resources_path(@resource.model_class, per_page: option, keep_query_params: true), class: 'hidden', 'data-per-page-option': option, 'data-turbo-frame': turbo_frame %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="flex">
    <div class="flex-2 sm:flex sm:items-center sm:justify-between">
      <%# @todo: add first & last page. make the first and last buttons rounded %>
      <% if @pagy.pages > 1 %>
        <%== pagy_nav @pagy %>
      <% end %>
    </div>
  </div>
</div>

app/views/avo/partials/_sortable_component.html.erb
<%
  icon = 'selector'

  if params[:sort_by] == field.id.to_s
    case params[:sort_direction]
      when 'asc'
        icon = 'sort-ascending'
      when 'desc'
        icon = 'sort-descending'
      end
  end
%>

<%= svg icon, class: 'inline-block fill-current text-gray-500 relative leading-none min-w-4 min-h-full ml-1 h-4' %>

app/views/avo/partials/_table_header.html.erb
<thead class="bg-blue-gray-100 border-t border-b border-gray-300 pb-1">
  <th>
    <!-- Select cell -->
  </th>
  <%
    fields.each_with_index do |field, index|
      if params[:sort_by] == field.id.to_s
        if params[:sort_direction] == 'asc'
          sort_by = nil
        else
          sort_by = field.id
        end

        if sort_by.present?
          case params[:sort_direction]
            when nil
              sort_direction = 'desc'
            when 'desc'
              sort_direction = 'asc'
            when 'asc'
              sort_direction = nil
            end
        else
          sort_direction = nil
        end
      else
        sort_by = field.id
        sort_direction = 'desc'
      end
      classes = "text-blue-gray-600 tracking-tight leading-tight text-xs font-semibold"
  %>
    <th class="text-left uppercase px-3 py-2 whitespace-nowrap">
      <% if field.sortable %>
        <%= link_to params.permit!.merge(sort_by: sort_by, sort_direction: sort_direction), class: "flex items-center #{classes} #{'cursor-pointer' if field.sortable}", 'data-turbo-frame': params[:turbo_frame] do %>
          <%= field.name %>
          <%= render partial: 'avo/partials/sortable_component', locals: {field: field} %>
        <% end %>
      <% else %>
          <div class="flex items-center <%= classes %>">
            <%= field.name %>
          </div>
      <% end %>
    </th>
  <% end %>

  <th class="w-24">
    <!-- Controls cell -->
  </th>
</thead>

app/views/avo/partials/_view_toggle_button.html.erb
<%
  if available_view_types.count > 1
    case view_type.to_sym
    when :table
      new_view_type = 'grid'
      new_icon = 'view-grid'
      translation_key = 'avo.grid_view'
    when :grid
      new_view_type = 'table'
      new_icon = 'view-list'
      translation_key = 'avo.table_view'
    end
%>
  <%= a_link params.permit!.merge(view_type: new_view_type), color: :blue, 'data-turbo-frame': turbo_frame, title: t('avo.switch_to_view', view_type: new_view_type), 'data-tippy': 'tooltip' do %>
    <%= svg new_icon %> <%= t translation_key, item: @resource.model_class.model_name.human.downcase %>
  <% end %>
<% end %>